### ISSUE TITLE
sample.py deprectaed warnings

### ISSUE THREAD

**Issue by fenrog** [sberl/supersid#14]
pi@supersid:~/supersid/supersid $ python3 sampler.py

sampler.py:64: DeprecationWarning: This function is deprecated. Please use the named parameter `channels` to `PCM()` instead
  self.inp.setchannels(1)
sampler.py:65: DeprecationWarning: This function is deprecated. Please use the named parameter `rate` to `PCM()` instead
  self.inp.setrate(audio_sampling_rate)
sampler.py:66: DeprecationWarning: This function is deprecated. Please use the named parameter `periodsize` to `PCM()` instead
  self.inp.setperiodsize(periodsize)
sampler.py:67: DeprecationWarning: This function is deprecated. Please use the named parameter `format` to `PCM()` instead
  self.inp.setformat(self.FORMAT)

can be solved by replacing
```
                 self.inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE,
                                          alsaaudio.PCM_NORMAL,
                                          card)
                 self.inp.setchannels(1)
                 self.inp.setrate(audio_sampling_rate)
                 self.inp.setperiodsize(periodsize)
                 self.inp.setformat(self.FORMAT)
```
with
```
                self.inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE,
                                         alsaaudio.PCM_NORMAL,
                                         channels=1,
                                         rate=audio_sampling_rate,
                                         format=self.FORMAT,
                                         periodsize=periodsize,
                                         device=card)
```

**Comment by sberl** [comment]
Fixed.
