### ISSUE TITLE
Is there a real need for the wx viewer?

### ISSUE THREAD

**Issue by fenrog** [sberl/supersid#27]
Would it be sufficient to bring all missing features to the tk viewer and to abandon the wx viewer?

[Python GUI programming](https://www.tutorialspoint.com/python/python_gui_programming.htm#:~:text=Tkinter%20Programming,to%20the%20Tk%20GUI%20toolkit.): Tkinter is the Python interface to the Tk GUI toolkit shipped with Python.

**Comment by sberl** [comment]
I would be in favor of getting rid of the wx viewer and committing to have just the text and tk viewers.
Do we know what the "missing features" are?

**Comment by fenrog** [comment]
see also https://github.com/fenrog/supersid/issues/14

sberl comment on this:
>Looks like all that really needs to be done is to add a "Plot" menu item to tk.
>Then we can drop wx completely.
>Then we can work on consistency between tk and text, but that's pretty low priority I think.

**Comment by fenrog** [comment]
ready for merge with pull request #44

**Comment by fenrog** [comment]
fixed with 3dcbdc95f4d67489888f4e33f71ad295aeb5d368, c33a9472cfb8c16c51fa6749061254085a4b6604, ea97cc0735827e4630a79960c7e88f0439dff5c7
