### ISSUE TITLE
unexpected config reader behaviour

### ISSUE THREAD

**Issue by fenrog** [sberl/supersid#29]
Behaviour of the Config class:

If it is initialized with a filename deviating from the default "supersid.cfg", then exactly this single file is read. This is an expected behaviour.

If it is initialized without a file name or with the default filename "supersid.cfg", then three files are read in this order:
    1) ../Config/supersid.cfg
    2) ./supersid.cfg
    3) ~/supersid.cfg or similar, the users home folder

The behaviour for the default name "supersid.cfg" may be surprising for the user. It is surprising for me. And I know of one more user who had issues with two supersid.cfg files, one in the Config/ and the second in the supersid/ folder. I personally would expect if I use "supersid.cfg" as parameter and this file exists in the current folder, then this file is read and nothing else.

An example for the actual behaviour. Let's assume there are thre supersid.cfg files in all three searched locations.
- First ../Config/supersid.cfg is read. It doesn't configure paper_size.
  This will result in the default paper_size = A4.
- Second ./supersid.cfg is read. It configures [PARAMETERS] paper_size = Legal.
  This will overloaded the paper_size = Legal.
- Third ~/supersid.cfg is read. It configures [PARAMETERS] paper_size = Letter.
  This will overloaded the paper_size = Letter.

If one really wants to have an automatic path detection, then I'd not go for a likely filename as "supersid.cfg" to trigger this cascaded reading, but I'd either use Pythons None or a special keyword like "CASCADE".

But I doubt this complexity is really needed. I'd recommend to remove it entirely. If one wants to have the configuration file in his home folder (i.e. because there are her/his mail credentials), then she/he can also put the entire configuration parameters into the hom e folder.

Proposed behaviour:
- If a configuration file name is given, then read this configuration file,
- else read ../Config/supersid.cfg.
- If none of both is present, stop with an error.

**Comment by sberl** [comment]
I like the idea of removing the "search path" behavior. I think the .cfg file location should be either in the default location, or explicitly provided on the command line with the -c option. All that other trying different locations will only cause confusion.

Also, I think the default location (../Config/supersid.cfg) should be relative to the script directory, and not to the current working directory of the shell that is invoking the command.

**Comment by fenrog** [comment]
The the default location `../Config/supersid.cfg` is relative to the script directory.
All scripts using the configuration file have a unique method to pass the configuration file:
- -c/--config path/to/supersid.cfg
- if omitted, the default location is used
- no cascaded config file reading anymore
