### ISSUE TITLE
Allow fixed range on live spectrum graph power axis.

### ISSUE THREAD

**Issue by sberl** [sberl/supersid#3]
Keith Payea via googlegroups.com | Keith Payea via googlegroups.com | 9:30 AM (1 hour ago) |   |  
-- | -- | -- | -- | --
Keith Payea via googlegroups.com
to sara-list | to sara-list
to sara-list

This isn’t a high priority change, just nice to have if possible.  Auto-ranging the live graph is very helpful during setup, but after a while it would be nice to set the range and leave it.  Then you can take a quick look at the spectrum and get an idea what’s going on without having to figure out the scale each time.

**Comment by fenrog** [comment]
ready for merge with pull request #44

**Comment by fenrog** [comment]
fixed with 94750cbaba887c04e59f3984bddd985b48ede774
