### ISSUE TITLE
support two channels of the sound card

### ISSUE THREAD

**Issue by fenrog** [sberl/supersid#45]
The idea is to connect two receivers with two antennas with different orientation to the left and right channel of the sound card.

New configuration options:
- channel, the channel to be used for the station, default 0 (the left channel), optional 1 (the right channel)
- Channels, the number of channels, default 1, optional 2
```
[STATION_1]
channel = 0

[STATION_2]
channel = 1

[Capture]
Channels = 2
```

Scripts to be adapted:
- config.py to support the new configuration options
- find_alsa_devices.py to support one and two channels
- sampler.py to support one and two channels for alsaaudio, sounddevice and pyaudio
- supersid.py to support one and two channels
- supersid_scanner.py to support one and two channels for pyaudio
- textsidviewer.py to support one and two channels
- tksidviewer.py to support one and two channels

**Comment by kunkleb** [comment]
What sound card are you thinking of using?  Would you use the "Line In" inputs or is there a device with two microphone inputs?  I am currently using the mic input of an [Audio Injector Zero](https://www.audioinjector.net/rpi-zero) .  It does have left and right channel Line In capability.

**Comment by fenrog** [comment]
In Windows (with a builtin Realtek sound card) I chose 'line in'. The microphone input comes with noise and echo cancelation. These are features which I'm not interresetd in, when measuring physical effectes.

Your card is different. If I get it right, the difference bewteen the two connection options is the bypass of the potentiometer.
> Direct line connector : Plug into the direct line (0.1" header) to bypass the potentiometer control.
> Volume control connector : Plug into the potentiometer (0.1" header) to use the potentiometer as a volume control.

Try both and compare the results.

**Comment by fenrog** [comment]
in test (https://github.com/fenrog/supersid/commit/3db4df86abd7e1582ef01dda4dcb68c172ff50ca)

**Comment by meteorkees** [comment]
Hi, first of all thx for sharing and maintaining this software. Really appreciated!
I have the  ' stereo raspberry pi sound card"  from Audioinjector and this one has two RCA input channels, left and right.

My idea, and as I see yours was/is as well, to hook one antenna to the left input and an other antenna on the right input.

Would be very nice to setup one antenna N/S and the other one E/W.

Thx in advance!
