### ISSUE TITLE
supersid.py python

### ISSUE THREAD

**Issue by kunkleb** [sberl/supersid#5]
I downloaded the supersid-master files and found that with my RPi 3B I had to use #!/usr/bin/python in the supersid.py file, as opposed to just #!python.

**Comment by fenrog** [comment]
According to Wikipedia, Shebangs must specify absolute paths (or paths relative to current working directory) to system executables.
[https://en.wikipedia.org/wiki/Shebang_(Unix)#Program_location](url)
For this reason `#!python` appears to be wrong.

A thread on stackoverflow discusses shebang in Python scripts.
[https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take?rq=1](url)
The highest ratet answer suggests the use of `#!/usr/bin/env python3` or `#!/usr/bin/env python2` while `#!/usr/bin/env python` should not be used, unless the script is compatible with Python 2.x and 3.x.

This statement seems to be inline with [https://www.python.org/dev/peps/pep-0394/](url).

Distributors are encouraged to change `python` shebangs to `python3` when python 3.x is supported.

Script publishers can write shebangs as `#!/usr/bin/env python`.

python.org states that Python 2 is no longer supported as of January 1st, 2020. [https://www.python.org/doc/sunset-python-2/](url).

This raises the question, whether one should not drop the Python 2 support and use the shebang `#!/usr/bin/env python3`? This would also limit testing efforts.

**Comment by sberl** [comment]
I'm in favor of dropping python 2.x support. I will simplify the code and the testing.
My vote would be for 

#!/usr/bin/env python3

**Comment by sberl** [comment]
Fixed. All runnable modules have #!/usr/bin/env python3 at the top.
