### ISSUE TITLE
supersid tk viewer spectrograph should use decimals instead of exponentials

### ISSUE THREAD

**Issue by sberl** [sberl/supersid#6]
Just another observation - using the tk viewer, the numbers in the lower right, showing the location of the cursor on the spectrograph are being shown in exponential notation.  In the previous version, Eric's, they were shown with six digits including decimals.

**Comment by fenrog** [comment]
See the status bar bottom right. Is this what you intend to see?

<img width="481" alt="issue6" src="https://user-images.githubusercontent.com/72250570/140410104-f587df57-b630-4d58-871f-2e740adf3686.png">

```
(supersid) E:\work\Python-Samples\fenrog\supersid\supersid>git diff tksidviewer.py
diff --git a/supersid/tksidviewer.py b/supersid/tksidviewer.py
index 29332ae..53409d9 100644
--- a/supersid/tksidviewer.py
+++ b/supersid/tksidviewer.py
@@ -17,6 +17,14 @@ import tkinter.messagebox as MessageBox
 import tkinter.filedialog as FileDialog


+class Formatter(object):
+    def __init__(self):
+        pass
+    def __call__(self, x, y):
+        strength = pow(10, (y/10.0))
+        return "frequency=%.0f  " % x + " power=%.3f  " % y + " strength=%.0f" % strength
+
+
 class tkSidViewer():
     """Create the Tkinter GUI."""

@@ -75,7 +83,7 @@ class tkSidViewer():
         self.canvas._tkcanvas.pack(side=tk.TOP, fill=tk.BOTH, expand=1)

         self.axes = self.psd_figure.add_subplot(111)
-        # self.axes.hold(False)
+        self.axes.format_coord = Formatter()

         # StatusBar
         self.statusbar_txt = tk.StringVar()
```

**Comment by sberl** [comment]
What's the "strength" value about?  Was that there before?

**Comment by fenrog** [comment]
Don't ask me about the physical meaning of strength. It was there on the wx viewer from where I copied both: formula and formatting.

**Comment by sberl** [comment]
Strength seems useless. It is just converting the logarithm decibels to a linear value (maybe voltage?). I think we should get rid of it. Will open a new issue for that.
