### ISSUE TITLE
Daily data files not stored in set default < ../Data> folder

### ISSUE THREAD

**Issue by meteorkees** [sberl/supersid#68]
Left <data_path = ../Data> but the daily files are not stored in the /Data folder but in the folder /home/pi/supersid/supersid
The hourly .csv files are stored in the folder /home/pi/supersid/Data as expected.

**Comment by sberl** [comment]
Could you paste the contents of your supersid.cfg file here?

**Comment by meteorkees** [comment]
[supersid.cfg.txt](https://github.com/sberl/supersid/files/11139027/supersid.cfg.txt)

I had to add .txt to the filename to get the file uploaded. Copy txt only gives a weird text layout.

**Comment by meteorkees** [comment]
Solved, sorry, looks I did not search well.

Yes, their some .csv data files are saved to /supersid/upersid but when I looked a bit better in the supersid/Data I found all three files, one for each station (2) and one with combined stations.

**Comment by sberl** [comment]
What are the dates on the files in supersid/supersid? The are probably older. You can delete them if you like. There should only be .py files in that directory.

**Comment by meteorkees** [comment]
![Screenshot from 2023-04-05 10-26-54](https://user-images.githubusercontent.com/75120846/230025989-a6b3a577-900c-496a-ae58-d68ca2b46705.png)

It looks like they are saved in /supersid/supersid/ as well in /supersid/Data
Maybe it has something to do with the fact that i changed to log_format = both_extended ??

**Comment by sberl** [comment]
Very odd. Looks like a bug to me. Let's keep this open for now.

**Comment by fenrog** [comment]
@meteorkees: Any idea when the files have been saved to supersid/supersid? Maybe an action in the GUI? A comand line script execution?

**Comment by fenrog** [comment]
further investigation without any finding regarding how the sid files could end up in the wrong folder
https://github.com/sberl/supersid/pull/161
