### ISSUE TITLE
email instructions for supersid_plot.py

### ISSUE THREAD

**Issue by kunkleb** [sberl/supersid#7]
Detailed instructions would be helpful in setting up supersid_plot.py with the -e (email) argument.
In my case. I had to modify line 79 s = smtplib..SMTP() to s = smtplib.SMTP('smtp.gmail.com', 587)
Also had to add s.starttls() after s.connect (mailserver, port=mailport)
Need instructions on how to create and insert a message into the email.

**Comment by fenrog** [comment]
I had to populate the [Email] section in supersid.cfg and to do the same changes as described by kunkleb in order to get a mail sent.

The line numbers may be different from the original source as I already fixed the time.clock deprecation warning.
```
diff --git a/sudiff --git a/supersid/supersid_plot.py b/supersid/supersid_plot.py
index 7588f77..d1caacc 100755
--- a/supersid/supersid_plot.py
+++ b/supersid/supersid_plot.py
@@ -80,9 +80,10 @@ def sendMail(config, To_mail, msgBody, PDFfile):
         msg.attach(att)

     # Establish an SMTP object by connecting to your mail server
-    s = smtplib.SMTP()
+    s = smtplib.SMTP(mailserver, mailport)
     print("Connect to:", mailserver, mailport)
     s.connect(mailserver, port=mailport)
+    s.starttls()
     if mailserveruser:
         s.login(mailserveruser, mailserverpasswd)
     # Send the email - real from, real to, extra headers and content ...
@@ -274,8 +275,7 @@ class SUPERSID_PLOT():
         if pdf or eMail:
             # in case option eMail is given
             # but not pdfpp = PdfPages(pdf or 'Image.pdf')
-            plt.savefig(pp, format='pdf')
-            pp.close()
+            plt.savefig(pdf or 'Image.pdf', format='pdf')
         if showPlot:
             plt.show()
         if eMail:
```

**Comment by fenrog** [comment]
There is some documentation in ConfigHelp.md but it is incomplete: email_port is not documented.

```
diff --git a/docs/ConfigHelp.md b/docs/ConfigHelp.md
index f89de59..d262452 100644
--- a/docs/ConfigHelp.md
+++ b/docs/ConfigHelp.md
@@ -73,8 +73,9 @@ This section can be omitted if you plan to use the 'pyaudio' library. If you wan

 ## [Email] ##
 The 'supersid_plot.py' program can send you an email with the attached plot as a PDF file. In order to use this feature, you must provide the information necessary to contact your email server as well as which email to use.
-  * from_mail: sender's emai
+  * from_mail: sender's email
   * to_mail: recipient's email
+  * email_port: email server's port (SMPT)
   * email_server: email server to use (SMPT)
   * email_login: [optional] if your server requires a login for identification
   * email_password: [optional] if your server requires a password for identification
@@ -87,4 +88,4 @@ Group all parameters to send data to an FTP server i.e. Standford data repositor
   * ftp_server: URL of the server (sid-ftp.stanford.edu)
   * ftp_directory: target folder on the FTP server where files should be written (on Standford's server: /incoming/SuperSID/NEW/)
   * local_tmp: local temporary directpry used to write the files before their upload
-  * call_signs: list of recorded stations to upload. Not all recorded stations might be of interrest: list only the most relevant one(s).
\ No newline at end of file
+  * call_signs: list of recorded stations to upload. Not all recorded stations might be of interrest: list only the most relevant one(s).

```

**Comment by kunkleb** [comment]
An explanation or example of the email_port would be helpful.  It took a lot of digging around but I finally found that I could use port 587 for gmail.  I then had to go through the following procedure to get gmail to work.  I wrote this up to help S. Aguirre (station 9450) get it working.  

Open the web browser.
Sign into your Google email account.
Then go into settings (gear icon) and allow less secure apps.
Settings > See all settings > Accounts and Import > Change account settings: Other Google Account Settings > Security > Less secure app access > Switch to On

**Comment by fenrog** [comment]
I'm not sure whether this issue should have been closed.
a) The documentation is not up to date.
b) I'm not using GMail and can't configure the server to be lazy regarding security. Thus I need TLS. If there are still servers around which do not support TLS, one needs one more configuration option in the [Email] section to enable/disable the use of TLS.

**Comment by kunkleb** [comment]
Sorry, that was my mistake by hitting close.
