### ISSUE TITLE
improvement: automatic detection of utc_offset and time_zone

### ISSUE THREAD

**Issue by fenrog** [sberl/supersid#78]
The configuration settings utc_offset and time_zone should be derived from PC/Pi time settings. Especially in countries with dailight saving time it is too easy not to update the changed settings twice a year.

general time usage:
- ftp_to_stanford.py uses UTC: `yesterday = datetime.utcnow() - timedelta(days=1)` - Used to calculate timestamp of yesterday.
- sidfile.py uses UTC: `utcnow = datetime.utcnow()`
- sidtimer.py uses UTC: `self.utc_now = datetime.utcnow()`
- supersid/supersid_plot.py uses local time: `Now = datetime.datetime.now()` - Used to calculate timestamp of today or yesterday. Update to match ftp_to_stanford.py

`utc_offset` usage:
- config.py: read the string from the configuration file
- sidfile.py: write the string to the header

`time_zone` usage:
- config.py: read the string from the configuration file
- sidfile.py: write the string to the header with a fallback to `self.sid_params['timezone']`

additonal findings:
- sidfile.py uses the non-existing `'timezone'` in self.sid_params; one finding; to be removed
- sidfile.py uses the non-existing `'loginterval'` in self.sid_params; three findings; to be removed
- sidfile.py uses the non-existing `'monitorid'` in self.sid_params; one finding; to be removed

**Comment by fenrog** [comment]
The problem to get a proper time_zone name is non-trivial.

English Ubuntu appears to be ok:
```
>>> import datetime
>>> datetime.datetime.now(datetime.timezone.utc).astimezone().strftime("%z")
'+0200'
>>> datetime.datetime.now(datetime.timezone.utc).astimezone().strftime("%Z")
'CEST'
```

German Windows shows German strings:
```
>>> import datetime
>>> datetime.datetime.now(datetime.timezone.utc).astimezone().strftime("%z")
'+0200'
>>> datetime.datetime.now(datetime.timezone.utc).astimezone().strftime("%Z")
'Mitteleuropäische Sommerzeit'
```

The following solution reports the same on both systems:
`pip3 install tzlocal`
```
>>> from tzlocal import get_localzone
>>> str(get_localzone())
'Europe/Berlin'
```

@sberl What are the expectations for `time_zone` reported in the file headers sent via FTP to Stanford University?

**Comment by fenrog** [comment]
The data files from 2024-05-30 are using very different formats for UTC_Offset and TimeZone. Partially the offest does not match the time zone. Format and values of both show no common scheme.

```
Site,UTC_Offset,TimeZone
AGUSA3,0,NONE
Agua-Caliente,-0.0,Mountain Standard Time
BNA215,-06:00,CST
Bedford,-5,EST
CAS,-4,EDT
CHSAC1,0,GMT
CaGrBa,-00:00,EST
CiniselloBalsamo,+2.00,CEST
DE_St_George2,+02:00,CEST
EvansGA,-00:00,Eastern
Fuller,-00.00,Eastern Standard ET
GHM,-06:00,MST
Hermosillo,-07:00,MDT
JPO,-7,PST
Jaap,02:00,CEST
K4UL-1,-04:00,America/New_York
KA6AKH,-05:00,Eastern Time (EST)
KB5FIO,-07:00,MST_Arizona_No_DST
KOLHAPUR-2,UTC+05:30,Indian Standard Time (IST)
Kiel-Wellsee,+02:00,UTC
LottObs,20,EDT
MARSDEN01,-06:00,Central Standard Time (CST)
MHO,-5,Eastern Time (US & Canada)
MHO2,-5,NONE
OBS,0,GMT
PTO_SID,0,CST
RoswellMeteor,-7,America/Denver
SCO,-5,UTC
SSRO,-6:00,MST
Sirius,-5,HNE
UTP,19,GMT
VA3ROM,-00:00,America/Thunder Bay
XHS,-5,EASTERN STANDARD TIME
YADA,-5,CST
ZSPDRE,1,CET
tjb,0,GMT
```

**Comment by sberl** [comment]
The local time is never used for anything in the software either on the client, or on the stanford server. 
I think the original vision was that the stanford web site would have an option display the plots in the local timezone of the user, but it was never implemented.
I think we can just leave the utc_offset parameter out, or just leave it as it is since nothing ever looks at the value.
We always have the option to go back later and derive the utc_offset from the (latitude, longitude, utc_time). I have code that does that in other contexts.

**Comment by fenrog** [comment]
> ... just leave it as it is since nothing ever looks at the value
