### ISSUE TITLE
time.clock deprecation warning

### ISSUE THREAD

**Issue by kunkleb** [sberl/supersid#8]
supersid_plot.py gives deprecation warning for time.clock
Looks like it should be replaced in the future with time.process_time

**Comment by fenrog** [comment]
can be solved as

diff --git a/supersid/supersid_plot.py b/supersid/supersid_plot.py
index 30b9b14..7588f77 100755
--- a/supersid/supersid_plot.py
+++ b/supersid/supersid_plot.py
@@ -42,6 +42,10 @@ import argparse
 from sidfile import SidFile
 from config import Config

+try:
+    clock = time.process_time
+except:
+    clock = time.clock

 def sendMail(config, To_mail, msgBody, PDFfile):
     """Send the mail using the smtplib module.
@@ -157,7 +161,7 @@ class SUPERSID_PLOT():
         colorStation = {}
         colorIdx = 0

-        time.clock()
+        clock()
         for filename in sorted(filenames):
             figTitle.append(os.path.basename(filename)[:-4]) # extension .csv assumed
             sFile = SidFile(filename)
@@ -230,7 +234,7 @@ class SUPERSID_PLOT():
                 # keep track of the days
                 daysList.add(sFile.startTime)

-        print ("All files read in", time.clock(), "sec.")
+        print ("All files read in", clock(), "sec.")

         if web:  # add the lines marking the retrieved flares from NOAA
             alternate = 0

**Comment by sberl** [comment]
Fixed
